name: Check Dependency Versions

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-versions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Create virtual environment
      run: |
        python -m venv venv
        echo "Virtual environment created"
    
    - name: Activate virtual environment and install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check code formatting with black
      run: |
        source venv/bin/activate
        black --check check_versions.py
    
    - name: Check import sorting with isort
      run: |
        source venv/bin/activate
        isort --check-only --diff check_versions.py
    
    - name: Run type checking with mypy
      run: |
        source venv/bin/activate
        mypy --strict check_versions.py
    
    - name: Run version check script
      run: |
        source venv/bin/activate
        python check_versions.py org.swaywm.sway/org.swaywm.sway.yaml