on:
  push:
    branches: [master]
  pull_request:
name: Build Flatpaks
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    strategy:
      matrix:
        arch:
          - x86_64
      fail-fast: true
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H:%M:%S')" >> $GITHUB_ENV
      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%s')" >> $GITHUB_ENV
      - name: Test Times
        run: echo "${{ env.date}}-${{ env.timestamp }}"
      - uses: actions/checkout@v4
      # Docker is required by the docker/setup-qemu-action which enables emulation
      - name: Install deps
        run: |
          dnf -y install docker
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.4
        with:
          bundle: sway.flatpak
          manifest-path: org.swaywm.sway/org.swaywm.sway.yaml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.timestamp }}
          name: >
            Sway flatpak from ${{ github.ref }} on ${{ env.date }}
          draft: true
          prerelease: true
          files: ./sway.flatpak
